### ISSUE TITLE
flickrapi.exceptions.FlickrError: Error: 108: Invalid frob

### ISSUE THREAD

**Issue by jstarcher** [jmahmood/Flickr-Cli#4]
I was playing with this script on OSX and was having an issue where the script would fail due to an Invalid Token or Frob before I could press authorize in the browser. It's actually an issue with flickerapi but I figured I'd put an issue here to make people aware.

Here is the code change I made to fix it:

```patch
--- __init__.py	2013-05-26 22:46:36.000000000 -0400
+++ /Library/Python/2.7/site-packages/flickrapi/__init__.py	2013-05-26 22:43:42.000000000 -0400
@@ -653,6 +653,7 @@
             browser = webbrowser.GenericBrowser(os.environ['BROWSER'])

         browser.open(auth_url, True, True)
+        ans = raw_input("Have you authenticated this application? (Y/N): ")

     def get_token_part_one(self, perms="read", auth_callback=None):
         """Get a token either from the cache, or make a new one from
```

**Comment by jmahmood** [comment]
I've made some changes to how we handle getting the frob, based on the changes in the FlickrAPI framework. A few years late but I think now this issue should not come back up (I managed to test this a few times and added a test case that works regardless of your situation wrt having a login cookie or not).

Years later, but I think we can mark this fixed.  If it comes up again, please let me know.
