### ISSUE TITLE
flickrapi.exceptions.FlickrError: Error: 112: Method "flickr.get.token.part.one" not found

### ISSUE THREAD

**Issue by dickinsonjl** [jmahmood/Flickr-Cli#7]
This seems to be a flickrAPI version issue. To fix I ran:
```
sudo pip uninstall flickrapi
sudo pip install -I flickrapi==1.4.5
```

Need to specify version in pip.txt

**Comment by jmahmood** [comment]
Thanks for the heads up.  Going to make a fix today.

**Comment by jmahmood** [comment]
Fixed in the change I pulled in earlier today.

**Comment by jmahmood** [comment]
FYI, there is a change in the dev branch which will be migrated over shortly which will allow us to user the latest version of Flickrapi.

**Comment by dickinsonjl** [comment]
Great. Looking forward to that ☺
